EDS_QUERY_API_URL: 'https://searchworks.stanford.edu/articles?q=%{q}&rows=%{max}&format=json'
EDS_QUERY_URL: 'https://searchworks.stanford.edu/articles?q=%{q}'
EDS_FETCH_URL: 'https://searchworks.stanford.edu/articles/%{id}'
CATALOG_QUERY_API_URL: 'https://searchworks.stanford.edu/?q=%{q}&rows=%{max}&format=json'
CATALOG_QUERY_URL: 'https://searchworks.stanford.edu/?q=%{q}'
CATALOG_FETCH_URL: 'https://searchworks.stanford.edu/view/%{id}'
LIBRARY_WEBSITE_QUERY_API_URL: 'https://library.stanford.edu/search/website?search=%{q}'
MAX_RESULTS: 3
CATALOG_HOME_URL: 'https://searchworks.stanford.edu'
ARTICLES_HOME_URL: 'https://searchworks.stanford.edu/articles'
LIBRARY_WEBSITE_HOME_URL: 'https://library.stanford.edu'
YEWNO_HOME_URL: 'https://stanford.idm.oclc.org/login?url=https://discover.yewno.com'
GLOBAL_ALERT: <%= false %>
ENABLED_SEARCHERS:
  - catalog
  - article
  - library_website
LIBGUIDES:
  API_URL: 'https://example.com/1.1/guides'
  SITE_ID: 123456
  KEY: abc1234
  NUM_RESULTS_SHOWN: 5
  QUERY_URL: 'https://guides.library.stanford.edu/srch.php?q=%{q}'
  HOME_URL: 'https://guides.library.stanford.edu/'

EXHIBITS:
  API_URL: 'https://exhibits.stanford.edu/exhibit_finder?q=%{q}'
  LINK_URL: 'https://exhibits.stanford.edu/%{id}'
  NUM_RESULTS_SHOWN: 5
  QUERY_URL: 'https://exhibits.stanford.edu/search?q=%{q}'
